apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb-deployment
  labels:
    app: ksqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
      - name: ksqldb
        image: confluentinc/ksqldb-server:0.28.2
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: PLAINTEXT://my-cluster-kafka-bootstrap:9092
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KSQL_KSQL_STREAMS_REPLICATION_FACTOR
          value: "1"
        - name: KSQL_KSQL_INTERNAL_TOPIC_REPLICAS
          value: "1"
        - name: KSQL_KSQL_STREAMS_NUM_STREAM_THREADS
          value: "1"
        - name: KSQL_CONFIG_DIR
          value: "/etc/ksqldb"
        - name: KSQL_KSQL_EXTENSION_DIR
          value: "/etc/ksqldb/ext/"
        volumeMounts:
        - name: ksqldb-volume
          mountPath: /tmp/kafka-streams/
      volumes:
        - name: ksqldb-volume
          persistentVolumeClaim:
            claimName: ksqldb-pv-claim