apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ksqldb-pv-claim
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi