CREATE STREAM NOT_BGC_MASTER_ARTICLE_ST (
    `MST_CINR` BIGINT,
    `MST_CINV` BIGINT,
    `MST_BARCODE` VARCHAR,
    `MST_DIV` VARCHAR,
    `MST_BRAND_CODE` VARCHAR,
    `MST_DEPT` VARCHAR,
    `MST_SDEPT` VARCHAR,
    `MST_CLASS` VARCHAR,
    `MST_SCLASS` VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'bigc_poc.public.BGC_MASTER_ARTICLE', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
);

--TBL
CREATE TABLE NOT_BGC_MASTER_ARTICLE_TB WITH (
    KAFKA_TOPIC = 'NOT_BGC_MASTER_ARTICLE_TB', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
  ) AS 
  SELECT
    `MST_CINR`as `MST_CINR`,
    LATEST_BY_OFFSET(`MST_CINV`, false) AS `MST_CINV`, -- text
    LATEST_BY_OFFSET(`MST_BARCODE`, false) AS `MST_BARCODE`,
    LATEST_BY_OFFSET(`MST_DIV`, false) AS `MST_DIV`, --oosFlag
    LATEST_BY_OFFSET(`MST_BRAND_CODE`, false) AS `MST_BRAND_CODE`,
    LATEST_BY_OFFSET(`MST_DEPT`, false) AS `MST_DEPT`,
    LATEST_BY_OFFSET(`MST_SDEPT`, false) AS `MST_SDEPT`,
    LATEST_BY_OFFSET(`MST_CLASS`, false) AS `MST_CLASS`,
    LATEST_BY_OFFSET(`MST_SCLASS`, false) AS `MST_SCLASS` --cateogryCode
  FROM NOT_BGC_MASTER_ARTICLE_ST
  GROUP BY `MST_CINR`
  EMIT CHANGES;