CREATE STREAM GOLD_ARTCAISSE_ST (
    `ACASITE` BIGINT,
    `ACAPRPERM` DOUBLE,
    `ACAPRIX` DOUBLE,
    `ACAIETI` BIGINT,
    `ACADDEB` TIMESTAMP,
    `ACADFIN` TIMESTAMP,
    `ACAPLTYPE` BIGINT,
    `ACACODE` VARCHAR,
    `ACACINV` VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'bigc_poc.public.GOLD_ARTCAISSE', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
);