CREATE STREAM GOLD_ARTCAISSE_ST (
    `ACASITE` BIGINT,
    `ACAPRPERM` DOUBLE,
    `ACAPRIX` DOUBLE,
    `ACAIETI` BIGINT,
    `ACADDEB` TIMESTAMP,
    `ACADFIN` TIMESTAMP,
    `ACAPLTYPE` BIGINT,
    `ACACODE` VARCHAR,
    `ACACINV` VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'bigc_poc.public.GOLD_ARTCAISSE', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
);

--TBL
CREATE TABLE MKP_MASTER_CONSTANT_TBL WITH (
    KAFKA_TOPIC = 'MKP_MASTER_CONSTANT_TBL', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
  ) AS 
  SELECT
    `NUMBER_TYPE` as `ROWKEY`,
    LATEST_BY_OFFSET(`ACASITE`, false) AS `storeCode`,
    LATEST_BY_OFFSET(`ACAPRPERM`, false) AS `normalPrice`,
    LATEST_BY_OFFSET(`ACAPRIX`, false) AS `curentPrice`,
    LATEST_BY_OFFSET(`ACAIETI`, false) AS `ACAIETI`, --active
    LATEST_BY_OFFSET(`ACADDEB`, false) AS `startDate`,
    LATEST_BY_OFFSET(`ACAPLTYPE`, false) AS `discountType`
  FROM MKP_MASTER_CONSTANT_ST
  GROUP BY `NUMBER_TYPE`
  EMIT CHANGES;