CREATE STREAM NOT_MKP_MASTER_CONSTANT_ST (
    `DESCRIPTION_NAME` VARCHAR,
    `NUMBER_TYPE` VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'bigc_poc.public.MKP_MASTER_CONSTANT', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
);

--TBL
CREATE TABLE NOT_MKP_MASTER_CONSTANT_TB WITH (
    KAFKA_TOPIC = 'NOT_MKP_MASTER_CONSTANT_TB', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
  ) AS 
  SELECT
    `NUMBER_TYPE` as `NUMBER_TYPE`,
    LATEST_BY_OFFSET(`DESCRIPTION_NAME`, false) AS `DESCRIPTION_NAME`
  FROM NOT_MKP_MASTER_CONSTANT_ST
  GROUP BY `NUMBER_TYPE`
  EMIT CHANGES;