CREATE STREAM MKP_MASTER_CONSTANT_ST (
    `DESCRIPTION_NAME` VARCHAR,
    `NUMBER_TYPE` VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'bigc_poc.public.MKP_MASTER_CONSTANT', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
);