CREATE STREAM NOT_MKP_MASTER_TYPE_ST (
    `NW_FOCUS` VARCHAR,
    `MKP_TYPE` VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'bigc_poc.public.MKP_MASTER_TYPE', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
);

--TBL
CREATE TABLE NOT_MKP_MASTER_TYPE_TB WITH (
    KAFKA_TOPIC = 'NOT_MKP_MASTER_TYPE_TB', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
  ) AS 
  SELECT
    `MKP_TYPE` as `MKP_TYPE`,
    LATEST_BY_OFFSET(`NW_FOCUS`, false) AS `NW_FOCUS`
  FROM NOT_MKP_MASTER_TYPE_ST
  GROUP BY `MKP_TYPE`
  EMIT CHANGES;

--JOIN
CREATE TALBE NOT_MASTER_TYPE_JOIN_MASTER_CONSTANT_TB WITH (
    KAFKA_TOPIC = 'NOT_MASTER_TYPE_JOIN_MASTER_CONSTANT_TB', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
  ) AS
  SELECT
    MMC.`DESCRIPTION_NAME` AS `typeName`,
    MMT.`NW_FOCUS` AS `networkSite`,
    MMT.`MKP_TYPE` as `typeCode`
  FROM 
    NOT_MKP_MASTER_TYPE_TB MMT JOIN NOT_MKP_MASTER_CONSTANT_TB MMC
    ON MMT.`MKP_TYPE` = MMC.`NUMBER_TYPE`
  EMIT CHANGES;
