CREATE STREAM MKP_MASTER_TYPE_ST (
    `NW_FOCUS` VARCHAR,
    `MKP_TYPE` VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'bigc_poc.public.MKP_MASTER_TYPE', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
);

--TBL
CREATE TABLE MKP_MASTER_TYPE_TBL WITH (
    KAFKA_TOPIC = 'MKP_MASTER_TYPE_TBL', 
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3
  ) AS 
  SELECT
    `MKP_TYPE` as `ROWKEY`,
    LATEST_BY_OFFSET(`MKP_TYPE`, false) AS `typeCode`,
    LATEST_BY_OFFSET(`NW_FOCUS`, false) AS `networkSite`,
    LATEST_BY_OFFSET(`ROWTIME`, false) AS `MKP_MASTER_TYPE_TS`
  FROM MKP_MASTER_TYPE_ST
  GROUP BY `MKP_TYPE`
  EMIT CHANGES;